title: Abigail Krug
logo: Docs/Assets/headshot.JPG
description: Solutions Engineer @ Deloitte
description: Linkedin Profile: https://www.linkedin.com/in/abigail-krug-17a802229/
theme: jekyll-theme-minimal
