title: Abby Krug - CS Portfolio
email: abbykrug00@gmail.com
logo: Docs/Assets/headshot.JPG
description: Solutions Engineer @ Deloitte | UVA 2025 Grad 
theme: jekyll-theme-minimal

author:
  name: Abby Krug
  github: abbyakrug
  linkedin: https://www.linkedin.com/in/abigail-krug-17a802229/
